In [43]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [44]:
import pandas as pd
import numpy as np

In [45]:
ratings = pd.read_csv('/content/drive/MyDrive/Semester-2/Recommendation System/Assignment_2/RAW_interactions.csv')
recipes = pd.read_csv('/content/drive/MyDrive/Semester-2/Recommendation System/Assignment_2/RAW_recipes.csv')

In [46]:
ratings.head()

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."

In [47]:
recipes.head()

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [48]:
# Checking for duplicates
print(ratings.duplicated().sum())
print(recipes.duplicated().sum())

0
0

In [49]:
print(ratings.shape)
print(recipes.shape)

(1132367, 5)
(231637, 12)

In [50]:
recipes.rename(columns={'id':'recipe_id'},inplace=True)
recipes.head()

,name,recipe_id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [51]:
ratings_with_name = ratings.merge(recipes, on='recipe_id')
ratings_with_name.head()

,user_id,recipe_id,date,rating,review,name,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...,white bean green chile pepper soup,495,1533,2002-09-21,"['weeknight', 'time-to-make', 'course', 'main-...","[204.8, 5.0, 9.0, 26.0, 24.0, 2.0, 10.0]",4,"['combine beans , onion , chilies , 1 / 2 teas...",easy soup for the crockpot.,"['great northern beans', 'yellow onion', 'dice...",9
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall...",white bean green chile pepper soup,495,1533,2002-09-21,"['weeknight', 'time-to-make', 'course', 'main-...","[204.8, 5.0, 9.0, 26.0, 24.0, 2.0, 10.0]",4,"['combine beans , onion , chilies , 1 / 2 teas...",easy soup for the crockpot.,"['great northern beans', 'yellow onion', 'dice...",9
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...,devilicious cookie cake delights,20,56824,2002-10-27,"['30-minutes-or-less', 'time-to-make', 'course...","[132.3, 11.0, 39.0, 5.0, 4.0, 11.0, 5.0]",5,"['blend together cake mix , oil and eggs', 'ad...",NaN,"[""devil's food cake mix"", 'vegetable oil', 'eg...",4
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...,baked potato toppings,10,64342,2004-02-25,"['15-minutes-or-less', 'time-to-make', 'course...","[2786.2, 342.0, 134.0, 290.0, 161.0, 301.0, 42.0]",3,['pick whichever topping you want to use and c...,these toppings sure makes a nice change from p...,"['mayonnaise', 'salsa', 'cheddar cheese', 'ref...",13
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin...",baked potato toppings,10,64342,2004-02-25,"['15-minutes-or-less', 'time-to-make', 'course...","[2786.2, 342.0, 134.0, 290.0, 161.0, 301.0, 42.0]",3,['pick whichever topping you want to use and c...,these toppings sure makes a nice change from p...,"['mayonnaise', 'salsa', 'cheddar cheese', 'ref...",13

In [52]:
X = ratings_with_name.groupby('user_id').count()['rating'] > 100
genuine_users = X[X].index
genuine_users

Int64Index([      1533,       1535,       2310,       2312,       3288,
                  4291,       4439,       4470,       4740,       5060,
            ...
               2206637,    2324285,    2399085,    2549237,    2597942,
            1800054678, 1802849661, 2000431901, 2000498330, 2001102678],
           dtype='int64', name='user_id', length=1368)

In [53]:
# Filtered ratings based on the users...
filtered_ratings = ratings_with_name[ratings_with_name['user_id'].isin(genuine_users)]

In [54]:
# Filtering Based on recipes...
y = filtered_ratings.groupby('name').count()['rating']>=50
famous_recipes = y[y].index

In [55]:
final_ratings = filtered_ratings[filtered_ratings['name'].isin(famous_recipes)]

In [56]:
# Dropping Duplicates if any
final_ratings.drop_duplicates()

,user_id,recipe_id,date,rating,review,name,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
4212,149363,96886,2005-05-11,5,This was awesome! Our whole family loved this ...,kittencal s spinach parmesan rice bake,40,89831,2004-08-04,"['60-minutes-or-less', 'time-to-make', 'course...","[351.2, 36.0, 3.0, 20.0, 35.0, 70.0, 5.0]",7,"['set oven to 350f', 'generously grease a 11 x...",this is a wonderful easy side dish to chicken ...,"['frozen chopped spinach', 'cooked white rice'...",13
4214,209441,96886,2005-06-06,5,"Awesome IS the word for this, I made this for ...",kittencal s spinach parmesan rice bake,40,89831,2004-08-04,"['60-minutes-or-less', 'time-to-make', 'course...","[351.2, 36.0, 3.0, 20.0, 35.0, 70.0, 5.0]",7,"['set oven to 350f', 'generously grease a 11 x...",this is a wonderful easy side dish to chicken ...,"['frozen chopped spinach', 'cooked white rice'...",13
4216,73836,96886,2005-09-07,5,This was scrumptious. I halved the recipe suc...,kittencal s spinach parmesan rice bake,40,89831,2004-08-04,"['60-minutes-or-less', 'time-to-make', 'course...","[351.2, 36.0, 3.0, 20.0, 35.0, 70.0, 5.0]",7,"['set oven to 350f', 'generously grease a 11 x...",this is a wonderful easy side dish to chicken ...,"['frozen chopped spinach', 'cooked white rice'...",13
4217,160974,96886,2005-09-11,5,I'm a spinach lover but the rest of the family...,kittencal s spinach parmesan rice bake,40,89831,2004-08-04,"['60-minutes-or-less', 'time-to-make', 'course...","[351.2, 36.0, 3.0, 20.0, 35.0, 70.0, 5.0]",7,"['set oven to 350f', 'generously grease a 11 x...",this is a wonderful easy side dish to chicken ...,"['frozen chopped spinach', 'cooked white rice'...",13
4218,195175,96886,2005-09-15,5,This makes a great side dish for company. It's...,kittencal s spinach parmesan rice bake,40,89831,2004-08-04,"['60-minutes-or-less', 'time-to-make', 'course...","[351.2, 36.0, 3.0, 20.0, 35.0, 70.0, 5.0]",7,"['set oven to 350f', 'generously grease a 11 x...",this is a wonderful easy side dish to chicken ...,"['frozen chopped spinach', 'cooked white rice'...",13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1123827,130531,131018,2014-12-14,5,I have been making this recipe for a couple of...,pulled pork crock pot,1110,50509,2005-07-25,"['time-to-make', 'course', 'main-ingredient', ...","[335.1, 10.0, 72.0, 24.0, 80.0, 10.0, 8.0]",26,"['slice one onion and place in crock pot', 'pu...","i found this pulled pork recipe years ago, and...","['pork roast', 'onions', 'ginger ale', 'barbec...",4
1123829,121690,131018,2015-01-08,5,I&#039;ve made this twice without substitution...,pulled pork crock pot,1110,50509,2005-07-25,"['time-to-make', 'course', 'main-ingredient', ...","[335.1, 10.0, 72.0, 24.0, 80.0, 10.0, 8.0]",26,"['slice one onion and place in crock pot', 'pu...","i found this pulled pork recipe years ago, and...","['pork roast', 'onions', 'ginger ale', 'barbec...",4
1123855,51931,131018,2015-11-29,5,I am reviewing the recipe two ways. One as wr...,pulled pork crock pot,1110,50509,2005-07-25,"['time-to-make', 'course', 'main-ingredient', ...","[335.1, 10.0, 72.0, 24.0, 80.0, 10.0, 8.0]",26,"['slice one onion and place in crock pot', 'pu...","i found this pulled pork recipe years ago, and...","['pork roast', 'onions', 'ginger ale', 'barbec...",4
1123860,59686,131018,2016-03-18,5,"Since we butcher our own meat, I used a 4-1/2 ...",pulled pork crock pot,1110,50509,2005-07-25,"['time-to-make', 'course', 'main-ingredient', ...","[335.1, 10.0, 72.0, 24.0, 80.0, 10.0, 8.0]",26,"['slice one onion and place in crock pot', 'pu...","i found this pulled pork recipe years ago, and...","['pork roast', 'onions', 'ginger ale', 'barbec...",4
1123868,481092,131018,2017-01-13,5,Easy but terrific. Huge hit.,pulled pork crock pot,1110,50509,2005-07-25,"['time-to-make', 'course', 'main-ingredient', ...","[335.1, 10.0, 72.0, 24.0, 80.0, 10.0, 8.0]",26,"['slice one onion and place in crock pot', 'pu...","i found this pulled pork recipe years ago, and...","['pork roast', 'onions', 'ginger ale', 'barbec...",4

In [57]:
# Creating Pivot Table...
pt = final_ratings.pivot_table(index='name',columns='user_id',values='rating')
pt.fillna(0,inplace=True)
pt

user_id,1533,1535,2310,2312,3288,4291,4439,4470,4740,5060,...,2123645,2206637,2324285,2549237,2597942,1800054678,1802849661,2000431901,2000498330,2001102678
name,,,,,,,,,,,,,,,,,,,,,
24k carrots,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 minute spicy garlic shrimp,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40 minute hamburger buns,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
absolute best ever lasagna,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
all purpose stir fry sauce brown garlic sauce,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ww 0 point weight watchers cabbage soup,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
yes virginia there is a great meatloaf,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
yummy crispy baked fish,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
yummy crunchy apple pie,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zesty oven baked fries,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
pt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311 entries, 24k carrots to zesty oven baked fries
Columns: 1351 entries, 1533 to 2001102678
dtypes: float64(1351)
memory usage: 3.2+ MB

In [82]:
# user_ratings = pt[1533]
# user_ratings = user_ratings[user_ratings!=0]
# user_ratings.index

Index(['chicken garlic bites', 'uncle bill s whipped shortbread cookies'], dtype='object', name='name')

In [ ]:
# pt.index.difference(user_ratings.index)

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
similarity_score = cosine_similarity(pt)

In [60]:
similarity_score.shape

(311, 311)

In [91]:
# similarity_scores = similarity_score[pt.index.get_loc('24k carrots')]

In [94]:
# numerator = (pt[1533] * similarity_scores).sum()
# # numerator

1.327545553733536

In [95]:
# similarity_scores.sum()

39.808281542767006

In [96]:
def predict_ratings(user_id):
    user_ratings = pt[user_id]
    user_ratings = user_ratings[user_ratings != 0]
    user_unrated_recipes = pt.index.difference(user_ratings.index)
    predicted_ratings = []
    for recipe_name in user_unrated_recipes:
        similarity_scores = similarity_score[pt.index.get_loc(recipe_name)]
        numerator = (pt[user_id] * similarity_scores).sum()
        denominator = similarity_scores.sum()
        if denominator == 0:
            predicted_rating = 0
        else:
            predicted_rating = numerator / denominator
        predicted_ratings.append((recipe_name, predicted_rating))
    return predicted_ratings

In [99]:
def recommend_recipes(user_id):
    predicted_ratings = predict_ratings(user_id)
    top_recipe_names = [recipe_name for recipe_name, predicted_rating in sorted(predicted_ratings, key=lambda x: x[1], reverse=True)[:10]]
    return top_recipe_names

In [100]:
recommend_recipes(1533)

['master brine recipe for meats',
 'easy peezy pizza dough  bread machine pizza dough',
 'impossible peanut butter cookies',
 'red lobster cheddar bay biscuits copycat',
 'crock pot garlic brown sugar chicken',
 'crock pot chicken vindaloo',
 'breakfast in a mug',
 'the best apple pie muffins ever',
 'crock pot whole chicken',
 'grilled cheese  diner style']

In [71]:
# def recommend(recipe_name):
#   # Fetching the index
#   index = np.where(pt.index == recipe_name)[0][0]
#   similar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]
#   print(similar_items)
#   for i in similar_items:
#     print(pt.index[i[0]])

In [72]:
# recommend('40 minute hamburger buns')

[(104, 0.18528230882276944), (91, 0.17180296247103494), (217, 0.14580650109042942), (51, 0.14508330776079892), (154, 0.144795536250837)]
dark chocolate cake
crispy ginger beef
pizza dough for thin crust pizza
brown rice and lentil casserole
kittencal s chocolate frosting icing