In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD

In [ ]:
Base_path ='/content/drive/MyDrive/RS Data/Assignment 2'

In [ ]:
raw_recipies = pd.read_csv(Base_path+"/RAW_recipes.csv")
int_train = pd.read_csv(Base_path+"/interactions_train.csv")
int_val = pd.read_csv(Base_path+"/interactions_validation.csv")
int_test = pd.read_csv(Base_path+"/interactions_test.csv")

In [ ]:
user_counts = int_train.groupby('user_id').count()

# filter the user counts DataFrame to include only users who have rated at least 20 items
user_counts_filtered = user_counts[user_counts['recipe_id'] >= 100]

# get the list of user IDs who have rated at least 20 items
users_with_20_items = user_counts_filtered.index.tolist()

# filter the original DataFrame to include only the users who have rated at least 20 items
df_filtered = int_train[int_train['user_id'].isin(users_with_20_items)]

# print the filtered DataFrame
print(df_filtered)

           user_id  recipe_id        date  rating     u       i
6             2312        780  2000-09-12     5.0  1674  127175
7             2312      51964  2000-09-26     5.0  1674  151793
8             2312       1232  2000-10-17     4.0  1674   15498
9             2312       4397  2000-10-17     5.0  1674   14380
11            2312        164  2000-10-20     5.0  1674   96573
...            ...        ...         ...     ...   ...     ...
698887      146742     278872  2018-12-16     5.0  2178   76230
698888      400708       5123  2018-12-17     5.0   560   72083
698892     1271506      53121  2018-12-17     5.0  2877   51525
698899      226867     363072  2018-12-18     5.0  3604   29101
698900  2000498330     314535  2018-12-19     5.0  2248   21514

[410249 rows x 6 columns]

In [ ]:
user_item_matrix = df_filtered.pivot_table(values='rating', index='user_id', columns='recipe_id')

# fill missing values with 0
user_item_matrix = user_item_matrix.fillna(0)

# print the user-item rating matrix
print(user_item_matrix)

recipe_id   38      40      45      46      49      52      58      62      \
user_id
1533           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
1535           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2310           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2312           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
3288           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
...            ...     ...     ...     ...     ...     ...     ...     ...
1800054678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
1802849661     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2000431901     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2000498330     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2001102678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0

recipe_id   63      66      ...  536401  536411  536643  536679  536726  \
user_id                     ...
1533           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
1535           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
2310           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
2312           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
3288           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
...            ...     ...  ...     ...     ...     ...     ...     ...
1800054678     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
1802849661     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
2000431901     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
2000498330     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0
2001102678     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0

recipe_id   536729  536990  537175  537319  537458
user_id
1533           0.0     0.0     0.0     0.0     0.0
1535           0.0     0.0     0.0     0.0     0.0
2310           0.0     0.0     0.0     0.0     0.0
2312           0.0     0.0     0.0     0.0     0.0
3288           0.0     0.0     0.0     0.0     0.0
...            ...     ...     ...     ...     ...
1800054678     0.0     0.0     0.0     0.0     0.0
1802849661     0.0     0.0     0.0     0.0     0.0
2000431901     0.0     0.0     0.0     0.0     0.0
2000498330     0.0     0.0     0.0     0.0     0.0
2001102678     0.0     0.0     0.0     0.0     0.0

[1165 rows x 142485 columns]

In [ ]:
users = user_item_matrix.index.tolist()

In [ ]:
normalised_mat = user_item_matrix - np.asarray([(np.mean(user_item_matrix, 1))]).T

In [ ]:
A = normalised_mat.T / np.sqrt(user_item_matrix.shape[0] - 1)

In [ ]:
print(A)

user_id    1533        1535        2310        2312        3288        \
recipe_id
38          -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
40          -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
45          -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
46          -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
49          -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
...               ...         ...         ...         ...         ...
536729      -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
536990      -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
537175      -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
537319      -0.000112   -0.000598   -0.000327   -0.000144   -0.000156
537458      -0.000112   -0.000598   -0.000327   -0.000144   -0.000156

user_id    4291        4439        4470        4740        5060        ...  \
recipe_id                                                              ...
38          -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
40          -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
45          -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
46          -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
49          -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
...               ...         ...         ...         ...         ...  ...
536729      -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
536990      -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
537175      -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
537319      -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...
537458      -0.000208    -0.00052   -0.002388   -0.000193   -0.001532  ...

user_id    2123645     2324285     2399085     2549237     2597942     \
recipe_id
38           0.116932   -0.000393   -0.000101   -0.000202   -0.000231
40          -0.000310   -0.000393   -0.000101   -0.000202   -0.000231
45          -0.000310   -0.000393   -0.000101   -0.000202   -0.000231
46          -0.000310   -0.000393   -0.000101   -0.000202   -0.000231
49          -0.000310   -0.000393   -0.000101   -0.000202   -0.000231
...               ...         ...         ...         ...         ...
536729      -0.000310   -0.000393   -0.000101   -0.000202   -0.000231
536990      -0.000310   -0.000393   -0.000101   -0.000202   -0.000231
537175      -0.000310   -0.000393   -0.000101   -0.000202   -0.000231
537319      -0.000310   -0.000393   -0.000101   -0.000202   -0.000231
537458      -0.000310   -0.000393   -0.000101   -0.000202   -0.000231

user_id    1800054678  1802849661  2000431901  2000498330  2001102678
recipe_id
38          -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
40          -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
45          -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
46          -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
49          -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
...               ...         ...         ...         ...         ...
536729      -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
536990      -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
537175      -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
537319      -0.000213   -0.000399   -0.000341   -0.000259   -0.000116
537458      -0.000213   -0.000399   -0.000341   -0.000259   -0.000116

[142485 rows x 1165 columns]

In [ ]:
U, S, V = np.linalg.svd(A,full_matrices=False)

In [ ]:
rating= np.load(Base_path+"/user_item_100.npy")
ratings = pd.DataFrame(rating)

In [ ]:
ratings

,0,1,2,3,4,5,6,7,8,9,...,142475,142476,142477,142478,142479,142480,142481,142482,142483,142484
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1162,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
!pip install surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting surprise
  Downloading surprise-0.1-py2.py3-none-any.whl (1.8 kB)
Collecting scikit-surprise
  Downloading scikit-surprise-1.1.3.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 KB 16.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-surprise->surprise) (1.2.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from scikit-surprise->surprise) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.8/dist-packages (from scikit-surprise->surprise) (1.7.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp38-cp38-linux_x86_64.whl size=3366579 sha256=3fd5b2d77fa0418fc7a5e28926f4b08c7b14b08428d252eeea1ffa08411cc6f9
  Stored in directory: /root/.cache/pip/wheels/af/db/86/2c18183a80ba05da35bf0fb7417aac5cddbd93bcb1b92fd3ea
Successfully built scikit-surprise
Installing collected packages: scikit-surprise, surprise
Successfully installed scikit-surprise-1.1.3 surprise-0.1

In [ ]:
from surprise import Dataset
from surprise import Reader 
reader = Reader(rating_scale=(1,5))
data = Dataset.load_from_df(int_train[['user_id','recipe_id','rating']],reader)

In [ ]:
from surprise import SVD
from surprise.model_selection import cross_validate
svd = SVD(verbose=True,n_epochs=5)
cross_validate(svd,data,measures=['RMSE'],cv=10,verbose=True)

Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Evaluating RMSE of algorithm SVD on 10 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Fold 6  Fold 7  Fold 8  Fold 9  Fold 10 Mean    Std
RMSE (testset)    0.9278  0.9252  0.9196  0.9076  0.9176  0.9197  0.9177  0.9094  0.9189  0.9151  0.9179  0.0059
Fit time          5.92    5.74    5.48    5.78    6.55    5.44    5.56    6.29    6.31    5.43    5.85    0.38
Test time         1.17    1.71    0.59    0.66    1.30    0.86    0.68    1.25    1.42    0.69    1.03    0.37

{'test_rmse': array([0.92783185, 0.92516469, 0.91963459, 0.90762447, 0.91763417,
        0.91972027, 0.91768652, 0.90940433, 0.91893925, 0.91513349]),
 'fit_time': (5.920226097106934,
  5.7399327754974365,
  5.483434677124023,
  5.780514240264893,
  6.546354055404663,
  5.442444562911987,
  5.5572733879089355,
  6.289532661437988,
  6.3079833984375,
  5.425183057785034),
 'test_time': (1.1692371368408203,
  1.7074000835418701,
  0.593109130859375,
  0.6590068340301514,
  1.2950782775878906,
  0.8634634017944336,
  0.6819241046905518,
  1.2481560707092285,
  1.4162380695343018,
  0.6856193542480469)}

In [ ]:
from surprise import SVD
from surprise.model_selection import cross_validate
svd = SVD(verbose=True,n_epochs=20)
cross_validate(svd,data,measures=['RMSE'],cv=3,verbose=True)

Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 5
Processing epoch 6
Processing epoch 7
Processing epoch 8
Processing epoch 9
Processing epoch 10
Processing epoch 11
Processing epoch 12
Processing epoch 13
Processing epoch 14
Processing epoch 15
Processing epoch 16
Processing epoch 17
Processing epoch 18
Processing epoch 19
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 5
Processing epoch 6
Processing epoch 7
Processing epoch 8
Processing epoch 9
Processing epoch 10
Processing epoch 11
Processing epoch 12
Processing epoch 13
Processing epoch 14
Processing epoch 15
Processing epoch 16
Processing epoch 17
Processing epoch 18
Processing epoch 19
Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 5
Processing epoch 6
Processing epoch 7
Processing epoch 8
Processing epoch 9
Processing epoch 10
Processing epoch 11
Processing epoch 12
Processing epoch 13
Processing epoch 14
Processing epoch 15
Processing epoch 16
Processing epoch 17
Processing epoch 18
Processing epoch 19
Evaluating RMSE of algorithm SVD on 3 split(s).

                  Fold 1  Fold 2  Fold 3  Mean    Std
RMSE (testset)    0.9231  0.9193  0.9241  0.9222  0.0021
Fit time          11.81   14.33   13.31   13.15   1.03
Test time         2.99    3.87    2.73    3.20    0.49

{'test_rmse': array([0.92312844, 0.91931402, 0.92410866]),
 'fit_time': (11.813751459121704, 14.328476667404175, 13.30601954460144),
 'test_time': (2.986955404281616, 3.8709957599639893, 2.7334704399108887)}

In [ ]:
svd.predict(uid=1676,iid=136683)

Prediction(uid=1676, iid=136683, r_ui=None, est=4.560646556664938, details={'was_impossible': False})

In [ ]:
trainset = data.build_full_trainset()

In [ ]:

# get the ratings for user 1
# user_ratings = trainset.ur[1]

# def generate_recommendation(user_id, data, svd):
#     user_ratings = data[user_id, :]
#     unrated_indices = np.where(user_ratings.toarray()[0] == 0)[0]
#     predictions = np.zeros((len(unrated_indices),))
#     for i, item_id in enumerate(unrated_indices):
#       predictions[i] = svd.predict(uid=user_id,iid=item_id)
#     predicted_ratings = pd.DataFrame({'item_id': unrated_indices, 'rating': predictions})

In [ ]:
user_id = 1676
user_items = [item[0] for item in trainset.ur[user_id]]
unrated_items = [item for item in trainset.all_items() if item not in user_items]
predictions = [svd.predict(user_id, item) for item in unrated_items]
recommended_items = sorted(predictions, key=lambda x: x.est, reverse=True)[:400]

# Print the recommended items
for recommendation in recommended_items:
    print(recommendation.iid, recommendation.est)